"""
Gemini API Client

This module is responsible ONLY for communicating with the Gemini API.
It does not perform financial analysis, calculations, or JSON parsing.
"""

import logging
import os
from typing import Optional
from dotenv import load_dotenv
import google.generativeai as genai

from backend.ai.config import GEMINI_MODEL

logger = logging.getLogger(__name__)

API_KEY_HELP_MESSAGE = (
    "\n"
    "================================================================================\n"
    "GEMINI API KEY REQUIRED:\n"
    "1. Get a valid Gemini API key from Google AI Studio:\n"
    "   https://aistudio.google.com/app/apikey\n"
    "2. Open the '.env' file in your project root.\n"
    "3. Set your API key:\n"
    "   GEMINI_API_KEY=your_actual_api_key_here\n"
    "================================================================================"
)

FALLBACK_MODELS = [
    "gemini-flash-latest",
    "gemini-2.0-flash",
    "gemini-pro-latest",
]


class GeminiClient:
    """Simple wrapper around the Gemini API."""

    def __init__(self, api_key: Optional[str] = None, model_name: Optional[str] = None) -> None:
        """
        Initialize the Gemini API client.

        Args:
            api_key: Optional Gemini API key. If not provided, loaded from .env.
            model_name: Optional model override. Defaults to GEMINI_MODEL from config.
        """
        load_dotenv()

        self.api_key = api_key or os.getenv("GEMINI_API_KEY")

        placeholders = {
            "YOUR_GEMINI_API_KEY_HERE",
            "your_gemini_api_key_here",
            "your_actual_api_key_here",
            "change_me",
        }

        if (
            not self.api_key
            or not self.api_key.strip()
            or self.api_key in placeholders
        ):
            raise ValueError(
                f"GEMINI_API_KEY is missing or set to a placeholder in .env file.{API_KEY_HELP_MESSAGE}"
            )

        genai.configure(api_key=self.api_key)
        self.model_name = model_name or GEMINI_MODEL
        self._init_model(self.model_name)

    def _init_model(self, name: str) -> None:
        """Initialize the GenerativeModel with JSON response configuration."""
        self.model_name = name
        self.model = genai.GenerativeModel(
            self.model_name,
            generation_config={"response_mime_type": "application/json"},
        )
        logger.info("Initialized GeminiClient with model: %s", self.model_name)

    def generate(self, prompt: str) -> str:
        """
        Send a prompt to Gemini and return the raw text response.
        Automatically falls back to alternative supported Gemini models if the selected model is deprecated/unavailable.

        Args:
            prompt: Prompt string.

        Returns:
            Raw text generated by Gemini.

        Raises:
            ValueError: If prompt is empty or API key is invalid.
            RuntimeError: If all candidate Gemini models fail.
        """
        if not prompt or not prompt.strip():
            raise ValueError("Prompt cannot be empty.")

        models_to_try = [self.model_name] + [m for m in FALLBACK_MODELS if m != self.model_name]

        last_exception = None
        for candidate_model in models_to_try:
            try:
                if candidate_model != self.model_name:
                    logger.warning("Primary model failed/unavailable. Falling back to: %s", candidate_model)
                    self._init_model(candidate_model)

                logger.info("Sending generation prompt to Gemini model: %s", self.model_name)
                response = self.model.generate_content(prompt)
                if not response or not response.text:
                    raise RuntimeError(f"Gemini API returned an empty response for model {self.model_name}.")
                logger.info("Successfully received response from Gemini API using model: %s", self.model_name)
                return response.text.strip()

            except Exception as exc:
                err_msg = str(exc)
                if (
                    "API_KEY_INVALID" in err_msg
                    or "API key not valid" in err_msg
                    or ("400" in err_msg and "API key" in err_msg)
                    or "PermissionDenied" in err_msg
                    or "Unauthenticated" in err_msg
                ):
                    logger.error("Invalid GEMINI_API_KEY encountered during request.")
                    raise ValueError(
                        f"Invalid GEMINI_API_KEY provided.{API_KEY_HELP_MESSAGE}"
                    ) from exc

                last_exception = exc
                logger.warning("Model '%s' failed with error: %s. Trying next candidate...", candidate_model, exc)

        logger.error("All Gemini candidate models failed. Last error: %s", last_exception)
        raise RuntimeError(f"Gemini API request failed across all candidate models: {last_exception}") from last_exception